// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace De.Dhoffmann.Mono.FullscreenPresentation.Droid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int frag_editdetail = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int frag_editslideslist = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int frags = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int lvSlides = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int tvName = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int webView = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Browser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Edit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditSlidesList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SlidesItem = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000c
			public const int Cancel = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int DlgNewPresentationError = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int DlgNewPresentationErrorNoName = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int DlgNewPresentationErrorPraesExists = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int DlgNewPresentationErstellen = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int DlgNewPresentationText = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int DlgNewPresentationTitle = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int EditTabInfo = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int ErrMsgTitle = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int ErrorNoExternalStorage = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int Ok = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int PresentationTyp_GoogleIO2012Slides = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int btnNewPresentation = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int tvChoosePresentation = 2130968577;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
