// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace De.Dhoffmann.Mono.FullscreenPresentation.Droid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int btnOpenFolder = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int btnPresent = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int btnRender = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int btnSave = 2131099666;
			
			// aapt resource value: 0x7f060026
			public const int etCompany = 2131099686;
			
			// aapt resource value: 0x7f060017
			public const int etContent = 2131099671;
			
			// aapt resource value: 0x7f06002a
			public const int etGithub = 2131099690;
			
			// aapt resource value: 0x7f060027
			public const int etGooglePlus = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int etName = 2131099685;
			
			// aapt resource value: 0x7f06001f
			public const int etSubTitle = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int etTitle = 2131099677;
			
			// aapt resource value: 0x7f060028
			public const int etTwitter = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int etWebsite = 2131099689;
			
			// aapt resource value: 0x7f060003
			public const int frag_editdetail = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int frag_editslideslist = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int frags = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout1 = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout3 = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int llEditDetail = 2131099664;
			
			// aapt resource value: 0x7f060016
			public const int llGoogleIOContent = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int llGoogleIOSettings = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int llGoogleIOWrapper = 2131099669;
			
			// aapt resource value: 0x7f060004
			public const int llPresentationFolder = 2131099652;
			
			// aapt resource value: 0x7f06002b
			public const int lvSlides = 2131099691;
			
			// aapt resource value: 0x7f060019
			public const int scrollView1 = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int svInfo = 2131099656;
			
			// aapt resource value: 0x7f06001a
			public const int tableLayout1 = 2131099674;
			
			// aapt resource value: 0x7f060021
			public const int tbtnAnimation = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int tbtnAreas = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int tbtnTouch = 2131099683;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f06001b
			public const int textView2 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int textView3 = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int textView4 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int textView5 = 2131099680;
			
			// aapt resource value: 0x7f060024
			public const int textView8 = 2131099684;
			
			// aapt resource value: 0x7f06000d
			public const int tvAppInfo = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int tvAppInfoHeadline = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int tvAppInfoLic = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int tvAppInfoLicHeadline = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int tvAppInfoUse = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int tvAppInfoUseHeadline = 2131099658;
			
			// aapt resource value: 0x7f06002c
			public const int tvName = 2131099692;
			
			// aapt resource value: 0x7f060006
			public const int tvPresentationPath = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int webView = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Browser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Edit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditDetailGoogleIO2012 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditSlidesList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SlidesItem = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040034
			public const int AppInfo = 2130968628;
			
			// aapt resource value: 0x7f040033
			public const int AppInfoHeadline = 2130968627;
			
			// aapt resource value: 0x7f040036
			public const int AppInfoLic = 2130968630;
			
			// aapt resource value: 0x7f040035
			public const int AppInfoLicHeadline = 2130968629;
			
			// aapt resource value: 0x7f040032
			public const int AppInfoUse = 2130968626;
			
			// aapt resource value: 0x7f040031
			public const int AppInfoUseHeadline = 2130968625;
			
			// aapt resource value: 0x7f04000e
			public const int Cancel = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int DlgNewPresentationError = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int DlgNewPresentationErstellen = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int DlgNewPresentationText = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int DlgNewPresentationTitle = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int DlgPresentationErrorNoName = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int DlgPresentationErrorPraesExists = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int DlgRenamePresentationErstellen = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int DlgRenamePresentationText = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int DlgRenamePresentationTitle = 2130968583;
			
			// aapt resource value: 0x7f040011
			public const int EditDetailSpeicherort = 2130968593;
			
			// aapt resource value: 0x7f040023
			public const int EditGoogleIOAuthor = 2130968611;
			
			// aapt resource value: 0x7f040025
			public const int EditGoogleIOCompany = 2130968613;
			
			// aapt resource value: 0x7f04001c
			public const int EditGoogleIOContent = 2130968604;
			
			// aapt resource value: 0x7f040029
			public const int EditGoogleIOGithub = 2130968617;
			
			// aapt resource value: 0x7f040026
			public const int EditGoogleIOGooglePlus = 2130968614;
			
			// aapt resource value: 0x7f040024
			public const int EditGoogleIOName = 2130968612;
			
			// aapt resource value: 0x7f04001d
			public const int EditGoogleIOSettings = 2130968605;
			
			// aapt resource value: 0x7f040020
			public const int EditGoogleIOSlideAnimation = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int EditGoogleIOSlideAreas = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int EditGoogleIOSubTitle = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int EditGoogleIOTitle = 2130968606;
			
			// aapt resource value: 0x7f040022
			public const int EditGoogleIOTouch = 2130968610;
			
			// aapt resource value: 0x7f040027
			public const int EditGoogleIOTwitter = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int EditGoogleIOWebsite = 2130968616;
			
			// aapt resource value: 0x7f040002
			public const int EditTabInfo = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int ErrMsgCouldNotOpenFileManager = 2130968594;
			
			// aapt resource value: 0x7f040009
			public const int ErrMsgTitle = 2130968585;
			
			// aapt resource value: 0x7f04002f
			public const int Error = 2130968623;
			
			// aapt resource value: 0x7f040018
			public const int ErrorMinimalPresentationCount = 2130968600;
			
			// aapt resource value: 0x7f04000f
			public const int ErrorNoExternalStorage = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int Ok = 2130968589;
			
			// aapt resource value: 0x7f040030
			public const int OnlyLandscape = 2130968624;
			
			// aapt resource value: 0x7f04002e
			public const int PleaseWait = 2130968622;
			
			// aapt resource value: 0x7f040010
			public const int PresentationTyp_GoogleIO2012Slides = 2130968592;
			
			// aapt resource value: 0x7f040015
			public const int PresentationsMenuCreate = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int PresentationsMenuDelete = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int PresentationsMenuRename = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int PresentationsMenuStart = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int PresentationsMenuTitle = 2130968595;
			
			// aapt resource value: 0x7f04002c
			public const int ProgressRenderPresentation = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int ToastErrorRenderPresentation = 2130968621;
			
			// aapt resource value: 0x7f04002b
			public const int ToastPresentationRendered = 2130968619;
			
			// aapt resource value: 0x7f04002a
			public const int ToastPresentationSaved = 2130968618;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04001b
			public const int btnPresent = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int btnRender = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int btnSave = 2130968601;
			
			// aapt resource value: 0x7f040001
			public const int tvChoosePresentation = 2130968577;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
